export { createUid, DEFAULT_PHONE, DEFAULT_PHOTO, DEFAULT_STATION, DEFAULT_BULK_ROW } from "./defaults";
export {
  FEATURE_FUEL_NAME,
  FEATURE_SERVICE_NAME,
  FUEL_TYPES,
  SERVICES,
  VALID_PHOTO_TAGS,
} from "./features";
